name: publish-docker
run-name: Publish Docker Images
on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: false
        default: ''
permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: package-lock.json
          node-version: 22

      - name: Installing Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint -ws

      - name: Update Console Version
        working-directory: ./console
        run: |
          if [ "${{ inputs.tag }}" != "" ]; then
            VERSION="${{ inputs.tag }}"
          else
            SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
            VERSION="${{ github.ref_name }}-$SHORT_SHA"
          fi
          sed -i "s|NEXT_PUBLIC_API_CLIENT_VERSION: \".*\"|NEXT_PUBLIC_API_CLIENT_VERSION: \"$VERSION\"|g" next.config.mjs

      - name: Build
        run: npm run build -ws

      - name: Publish Image
        uses: littlehorse-enterprises/publish-image@v1
        with:
          image-name: lh-user-tasks-bridge-console
          dockerfile: ./console/Dockerfile
          context: ./console
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
          ghcr-root: true
