name: build and publish
on:
  workflow_call:
    inputs:
      version:
        type: string
        default: main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "corretto"

      - name: Test and Build Artifact
        run: ./gradlew api:build

      - uses: actions/upload-artifact@v4
        with:
          name: user-tasks-api-jar
          path: api/build/libs

  build-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Clone UI
        uses: actions/checkout@v4
        with:
          repository: littlehorse-enterprises/lh-user-tasks-ui
          path: lh-user-tasks-ui
          ref: main
          token: ${{ secrets.PAT_LH_USER_TASKS_UI }}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build UI
        working-directory: lh-user-tasks-ui
        run: |
          npm ci
          npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: user-tasks-ui
          include-hidden-files: true
          path:  |
            lh-user-tasks-ui/.next/standalone
            lh-user-tasks-ui/.next/static
            lh-user-tasks-ui/public

  docker:
    runs-on: ubuntu-latest
    needs:
      - test-and-build
      - build-ui
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download API Artifact
        uses: actions/download-artifact@v4
        with:
          name: user-tasks-api-jar
          path: ./build/libs/

      - name: Download UI Artifact
        uses: actions/download-artifact@v4
        with:
          name: user-tasks-ui
          path: ./

      - name: Build and Publish
        id: publish-image
        uses: littlehorse-enterprises/publish-image@v1
        with:
          image-name: lh-user-tasks-api
          registry: ecr
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch

      - name: Build and Publish Standalone
        id: publish-standalone-image
        uses: littlehorse-enterprises/publish-image@v1
        with:
          image-name: lh-user-tasks-standalone
          dockerfile: standalone/Dockerfile
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: littlehorse+github
          password: ${{ secrets.QUAY_REGISTRY_SECRET }}

      - name: Get image
        id: get-image
        run: |
          image=$(echo "${{ steps.publish-image.outputs.tags }}" | head -n 1)
          echo "IMAGE=${image}" >> $GITHUB_ENV
      - name: Push image to Quay
        run: |
          docker buildx imagetools create \
            --tag quay.io/littlehorse/lh-user-tasks-api:${{ inputs.version }} \
            ${IMAGE}
