name: build and publish
on:
  repository_dispatch:
    types:
      - build
  workflow_call:
    inputs:
      version:
        type: string
        default: main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "corretto"

      - name: Test and Build Artifact
        run: ./gradlew backend:build

      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lh-user-tasks-bridge-backend-jar
          path: backend/build/libs

  build-console:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Console
        uses: actions/checkout@v4
        with:
          repository: littlehorse-enterprises/lh-user-tasks-bridge
          path: lh-user-tasks-bridge
          ref: main
          token: ${{ secrets.PAT_LH_USER_TASKS_UI }}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Update Console Version
        working-directory: lh-user-tasks-bridge/console
        run: |
          if [ "${{ inputs.version }}" != "" ]; then
            VERSION="${{ inputs.version }}"
          else
            SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
            VERSION="${{ github.ref_name }}-$SHORT_SHA"
          fi
          sed -i "s|NEXT_PUBLIC_VERSION: \".*\"|NEXT_PUBLIC_VERSION: \"$VERSION\"|g" next.config.ts

      - name: Build Console
        working-directory: lh-user-tasks-bridge
        run: |
          npm install
          npm run build -ws
      
      - name: Build Demo Workflow
        working-directory: lh-user-tasks-bridge/demo-workflow
        run: |
          ./gradlew build

      - name: Upload Console Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lh-user-tasks-bridge-console
          include-hidden-files: true
          path:  |
            lh-user-tasks-bridge/console/.next/standalone
            lh-user-tasks-bridge/console/.next/static
            lh-user-tasks-bridge/node_modules

      - name: Upload Demo Workflow Jar Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lh-user-tasks-bridge-demo-jar
          include-hidden-files: true
          path: |
            lh-user-tasks-bridge/demo-workflow/build/libs/lh-user-tasks-bridge-demo-all.jar

      - name: Upload Demo Workflow Sh Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lh-user-tasks-bridge-demo-sh
          include-hidden-files: true
          path: |
            lh-user-tasks-bridge/demo-workflow/configure-littlehorse.sh

  docker:
    runs-on: ubuntu-latest
    needs:
      - test-and-build
      - build-console
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Backend Artifact
        uses: actions/download-artifact@v4
        with:
          name: lh-user-tasks-bridge-backend-jar
          path: ./backend/build/libs/

      - name: Download Console Artifact
        uses: actions/download-artifact@v4
        with:
          name: lh-user-tasks-bridge-console
          path: ./

      - name: Download Demo Workflow Jar Artifact
        uses: actions/download-artifact@v4
        with:
          name: lh-user-tasks-bridge-demo-jar
          path: ./demo-workflow/build/libs

      - name: Download Demo Workflow Sh Artifact
        uses: actions/download-artifact@v4
        with:
          name: lh-user-tasks-bridge-demo-sh
          path: ./demo-workflow

      - name: Build and Publish Backend
        id: publish-image
        uses: littlehorse-enterprises/publish-image@v1
        with:
          image-name: lh-user-tasks-bridge-backend
          dockerfile: Dockerfile
          registry: ecr

      - name: Build and Publish Standalone
        id: publish-standalone-image
        uses: littlehorse-enterprises/publish-image@v1
        with:
          image-name: lh-user-tasks-bridge-standalone
          dockerfile: standalone/Dockerfile
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: littlehorse+github
          password: ${{ secrets.QUAY_REGISTRY_SECRET }}

      - name: Get image
        id: get-image
        run: |
          image=$(echo "${{ steps.publish-image.outputs.tags }}" | head -n 1)
          echo "IMAGE=${image}" >> $GITHUB_ENV
      - name: Push image to Quay
        run: |
          docker buildx imagetools create \
            --tag quay.io/littlehorse/lh-user-tasks-bridge-backend:${{ inputs.version }} \
            ${IMAGE}
