name: build and publish
on:
  repository_dispatch:
    types:
      - build
  workflow_call:
    inputs:
      version:
        type: string
        default: main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "corretto"

      - name: Test and Build Artifact
        run: ./gradlew backend:build

      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lh-user-tasks-bridge-backend-jar
          path: backend/build/libs

  build-console:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Update Console Version
        working-directory: .
        run: |
          if [ "${{ inputs.version }}" != "" ]; then
            VERSION="${{ inputs.version }}"
          else
            SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
            VERSION="${{ github.ref_name }}-$SHORT_SHA"
          fi
          sed -i "s|NEXT_PUBLIC_VERSION: \".*\"|NEXT_PUBLIC_VERSION: \"$VERSION\"|g" /home/runner/work/lh-user-tasks-bridge/console/next.config.mjs

      - name: Build Console
        working-directory: .
        run: |
          npm install
          npm run build -ws

      - name: Build Demo Workflow
        working-directory: ./demo-workflow
        run: |
          ./gradlew build

      - name: Upload Console Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lh-user-tasks-bridge-console
          include-hidden-files: true
          path:  |
            lh-user-tasks-bridge/console/.next/standalone
            lh-user-tasks-bridge/console/.next/static
            lh-user-tasks-bridge/node_modules

      - name: Upload Demo Workflow Jar Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lh-user-tasks-bridge-demo-jar
          include-hidden-files: true
          path: |
           ./demo-workflow/build/libs/lh-user-tasks-bridge-demo-all.jar

      - name: Upload Demo Workflow Sh Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lh-user-tasks-bridge-demo-sh
          include-hidden-files: true
          path: |
            ./demo-workflow/configure-littlehorse.sh

  docker:
    runs-on: ubuntu-latest
    needs:
      - test-and-build
      - build-console
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Backend Artifact
        uses: actions/download-artifact@v4
        with:
          name: lh-user-tasks-bridge-backend-jar
          path: ./backend/build/libs/

      - name: Download Console Artifact
        uses: actions/download-artifact@v4
        with:
          name: lh-user-tasks-bridge-console
          path: ./

      - name: Download Demo Workflow Jar Artifact
        uses: actions/download-artifact@v4
        with:
          name: lh-user-tasks-bridge-demo-jar
          path: ./demo-workflow/build/libs

      - name: Download Demo Workflow Sh Artifact
        uses: actions/download-artifact@v4
        with:
          name: lh-user-tasks-bridge-demo-sh
          path: ./demo-workflow

      - name: Build and Publish Backend
        id: publish-image
        uses: littlehorse-enterprises/publish-image@v1
        with:
          image-name: lh-user-tasks-bridge-backend
          dockerfile: Dockerfile
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ghcr-root: true

      - name: Build and Publish Standalone
        id: publish-standalone-image
        uses: littlehorse-enterprises/publish-image@v1
        with:
          image-name: lh-user-tasks-bridge-standalone
          dockerfile: standalone/Dockerfile
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
          ghcr-root: true
